name: FamousQuotes build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the project
      run: sh gradlew build
    
    - name: Generate the static site
      run: sh gradlew run
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs




